export default COLOR_CONSTANTS = {
  COLOR_DARKEST: "#990000",
  COLOR_DARK: "#FF5B00",
  COLOR_LIGHT: "grey",
  COLOR_LIGHTEST: "#FFFFFF",

  COLOR_TEXT_LIGHT: "#ffffff",
  COLOR_TEXT_DARK: "#000000",
};
